[package]
name = "auditorium"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["ws"] }
include_dir = "0.7.4"
mime_guess = "2.0.5"
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
orchestra = { path = "../orchestra" }
futures = "0.3.31"
tracing = "0.1.41"
reqwest-eventsource = "0.6.0"
serde_json = "1.0.137"
tracing-subscriber = "0.3.19"

[features]
frontend = []
